export const MOCK_CUSTOMERS = [
  {
    id: '1',
    name: 'João Silva',
    phone: '(11) 98765-4321',
    lastVisit: '2023-10-25',
    visits: 15,
    spend: 950,
    stamps: 11,
    vip: true,
    bday: true,
  },
  {
    id: '2',
    name: 'Carlos Santos',
    phone: '(11) 91234-5678',
    lastVisit: '2023-08-10',
    visits: 3,
    spend: 180,
    stamps: 3,
    vip: false,
    bday: false,
  },
  {
    id: '3',
    name: 'Roberto Almeida',
    phone: '(11) 99999-8888',
    lastVisit: '2023-11-01',
    visits: 8,
    spend: 450,
    stamps: 8,
    vip: false,
    bday: false,
  },
  {
    id: '4',
    name: 'Fernando Costa',
    phone: '(11) 97777-6666',
    lastVisit: '2023-07-20',
    visits: 1,
    spend: 60,
    stamps: 1,
    vip: false,
    bday: false,
  },
  {
    id: '5',
    name: 'Marcos Paulo',
    phone: '(11) 95555-4444',
    lastVisit: '2023-10-15',
    visits: 20,
    spend: 1200,
    stamps: 5,
    vip: true,
    bday: false,
  },
]

export const MOCK_APPOINTMENTS = [
  {
    id: '1',
    time: '09:00',
    customer: 'João Silva',
    service: 'Corte + Barba',
    status: 'Confirmado',
    barber: 'Thiago',
  },
  {
    id: '2',
    time: '10:30',
    customer: 'Carlos Santos',
    service: 'Corte',
    status: 'Agendado',
    barber: 'Felipe',
  },
  {
    id: '3',
    time: '14:00',
    customer: 'Roberto Almeida',
    service: 'Barba',
    status: 'Concluído',
    barber: 'Thiago',
  },
]

export const MOCK_TRANSACTIONS = [
  {
    id: '1',
    date: '2023-11-02 14:30',
    desc: 'Serviço: Barba (Roberto Almeida)',
    type: 'in',
    amount: 45,
    method: 'PIX',
  },
  {
    id: '2',
    date: '2023-11-02 10:00',
    desc: 'Compra de Produtos - Fornecedor A',
    type: 'out',
    amount: 350,
    method: 'Transferência',
  },
  {
    id: '3',
    date: '2023-11-01 18:00',
    desc: 'Serviço: Corte + Barba (João Silva)',
    type: 'in',
    amount: 85,
    method: 'Cartão de Crédito',
  },
]
